import { Colors } from "@hova-labs/bento-box-web";

export const colorsLightTheme: Colors = {
  onBackground: "var(--hova-labs-on-background)",
  onSurface1: "var(--hova-labs-on-surface-1)",
  onSurface2: "var(--hova-labs-on-surface-2)",
  onPrimary: "var(--hova-labs-on-primary)",
  onSecondary: "var(--hova-labs-on-secondary)",
  background: "var(--hova-labs-background)",
  surface1: "var(--hova-labs-surface-1)",
  surface2: "var(--hova-labs-surface-2)",
  primary: "var(--hova-labs-primary)",
  secondary: "var(--hova-labs-secondary)",
  onBackgroundRaw: "hsla(220, 7%, 8%, 1)",
  onSurface1Raw: "hsla(220, 7%, 8%, 1)",
  onSurface2Raw: "hsla(220, 7%, 8%, 1)",
  onPrimaryRaw: "hsla(0, 0%, 100%, 1)",
  onSecondaryRaw: "hsla(0, 0%, 95%, 1)",
  backgroundRaw: "hsla(0, 0%, 100%, 1)",
  surface1Raw: "hsla(0, 0%, 90%, 1)",
  surface2Raw: "hsla(0, 0%, 80%, 1)",
  primaryRaw: "hsla(206, 31%, 45%,1)",
  secondaryRaw: "hsla(206, 31%, 25%,1)",
};

export const colorsDarkTheme: Colors = {
  onBackground: "var(--hova-labs-on-background)",
  onSurface1: "var(--hova-labs-on-surface-1)",
  onSurface2: "var(--hova-labs-on-surface-2)",
  onPrimary: "var(--hova-labs-on-primary)",
  onSecondary: "var(--hova-labs-on-secondary)",
  background: "var(--hova-labs-background)",
  surface1: "var(--hova-labs-surface-1)",
  surface2: "var(--hova-labs-surface-2)",
  primary: "var(--hova-labs-primary)",
  secondary: "var(--hova-labs-secondary)",
  onBackgroundRaw: "hsla(0, 0%, 100%, 1)",
  onSurface1Raw: "hsla(0, 0%, 100%, 1)",
  onSurface2Raw: "hsla(0, 0%, 100%, 1)",
  onPrimaryRaw: "hsla(0, 0%, 95%, 1)",
  onSecondaryRaw: "hsla(0, 0%, 0%, 1)",
  backgroundRaw: "	hsl(0, 0%, 7%)",
  surface1Raw: "hsl(0, 0%, 12%)",
  surface2Raw: "hsl(0, 0%, 18%)",
  primaryRaw: "hsla(206, 31%, 45%,1)",
  secondaryRaw: "hsla(206, 31%, 25%,1)",
};
